version: "3"
services:
    jupyter:
        image: jupyter/datascience-notebook
        working_dir: /code
        volumes:
            - .:/code
        ports:
            - 8888:8888
        container_name: competitive_nb
    python:
        build: ./
        tty: true
        stdin_open: true
        volumes:
            - "./:/code/"
        container_name: python3
    c920:
        build:
            context: ./
            dockerfile: Dockerfile_c
        tty: true
        stdin_open: true
        volumes:
            - "./:/code/"
        container_name: c920